let projects = [
	{
		type: 'text',
		description: 'welcome...\n\n here are a few projects',
	},
	{
		type: 'text',
		description: 'hard-surface modeling',
	},
	{
		type: 'image',
		src: './images/drone3.jpg',
		name: 'drone',
		description: '',
	},
	{
		type: 'image',
		src: './images/edgework1.jpg',
		name: 'edgework1',
		description: '',
	},
	{
		type: 'image',
		src: './images/crate.jpg',
		name: 'crate',
		description: '',
	},
	{
		type: 'image',
		src: './images/doorway.jpg',
		name: 'doorway',
		description: '',
	},
	{
		type: 'image',
		src: './images/dreams.jpg',
		name: '|||',
		description: '',
	},
	{
		type: 'image',
		src: './images/UI.jpg',
		name: 'UI',
		description: 'concept holo table',
	},
	{
		type: 'image',
		src: './images/triste.jpg',
		name: 'window',
		description: 'congrete window in verdun',
	},
	{
		type: 'text',
		description: 'animation',
	},
	{
		type: 'video',
		src: './videos/glasParticlesColored_high422_21.mp4',
		name: 'glasParticles',
		description: 'glasParticles - video loop',
	},
	{
		type: 'text',
		description: 'photogrammetry',
	},
	{
		type: 'image',
		src: './images/root.jpg',
		name: 'root',
		description: '',
	},
	{
		type: 'text',
		description: 'abstract',
	},
	{
		type: 'image',
		src: './images/yeti.jpg',
		name: 'untitled',
		description: '',
	},
	{
		type: 'image',
		src: './images/princessBubbleGum1.jpg',
		name: 'untitled',
		description: '',
	},
	{
		type: 'image',
		src: './images/nebula1.jpg',
		name: 'nebula',
		description: 'nebula - volume render experiment',
	},
	{
		type: 'image',
		src: './images/musgrave2.jpg',
		name: 'untitled',
		description: '',
	},
	{
		type: 'image',
		src: './images/musgrave3.jpg',
		name: 'untitled',
		description: '',
	},
	{
		type: 'image',
		src: './images/musgrave5.jpg',
		name: 'untitled',
		description: '',
	},
	{
		type: 'image',
		src: './images/hdis.jpg',
		name: 'hdis',
		description: '',
	},
	{
		type: 'image',
		src: './images/bw.jpg',
		name: 'BW',
		description: '',
	},
	{
		type: 'text',
		description: 'coding',
	},
	{
		type: 'image',
		src: './images/YouTubeHistory_all.svg',
		name: 'MYTH',
		description: 'My YouTube History - displays data of all videos, which where watched between mid 2016 and end 2019',
	},
	{
		type: 'image',
		src: './images/quakes3.jpg',
		name: 'quakes',
		description: 'earthquake data transformed into circles',
	},
];
