export let projects = [
	{
		type: 'text',
		description: 'welcome...\n\n here are a few projects',
	},
	{
		type: 'text',
		description: 'hard-surface modeling',
	},
	{
		type: 'image',
		src: new URL('../images/drone.jpg', import.meta.url).href,
		name: 'drone',
		description: '',
	},
	{
		type: 'image',
		src: new URL('../images/edgework1.jpg', import.meta.url).href,
		name: 'edgework1',
		description: '',
	},
	{
		type: 'image',
		src: new URL('../images/vaccinator.jpg', import.meta.url).href,
		name: 'vaccinator',
		description: '',
	},
	{
		type: 'image',
		src: new URL('../images/crate.jpg', import.meta.url).href,
		name: 'crate',
		description: '',
	},
	{
		type: 'image',
		src: new URL('../images/doorway.jpg', import.meta.url).href,
		name: 'doorway',
		description: '',
	},
	{
		type: 'image',
		src: new URL('../images/dreams.jpg', import.meta.url).href,
		name: '|||',
		description: '',
	},
	{
		type: 'image',
		src: new URL('../images/UI.jpg', import.meta.url).href,
		name: 'UI',
		description: 'concept holo table',
	},
	{
		type: 'image',
		src: new URL('../images/triste.jpg', import.meta.url).href,
		name: 'window',
		description: 'congrete window in verdun',
	},
	{
		type: 'text',
		description: 'animation',
	},
	{
		type: 'video',
		src: new URL('../videos/ZP.mp4', import.meta.url).href,
		name: 'Zorgon Peterson',
		description: '',
	},
	{
		type: 'video',
		src: new URL('../videos/SaudKruger.mp4', import.meta.url).href,
		name: 'Saud Kruger',
		description: '',
	},
	{
		type: 'video',
		src: new URL('../videos/glasParticlesColored_high422_21.mp4', import.meta.url).href,
		name: 'glasParticles',
		description: 'glasParticles - video loop',
	},
	{
		type: 'text',
		description: 'photogrammetry',
	},
	{
		type: 'image',
		src: new URL('../images/root.jpg', import.meta.url).href,
		name: 'root',
		description: '',
	},
	{
		type: 'text',
		description: 'abstract',
	},
	{
		type: 'image',
		src: new URL('../images/HairFrame.jpg', import.meta.url).href,
		name: 'untitled',
		description: '',
	},
	{
		type: 'image',
		src: new URL('../images/yeti.jpg', import.meta.url).href,
		name: 'untitled',
		description: '',
	},
	{
		type: 'image',
		src: new URL('../images/princessBubbleGum1.jpg', import.meta.url).href,
		name: 'untitled',
		description: '',
	},
	{
		type: 'image',
		src: new URL('../images/nebula1.jpg', import.meta.url).href,
		name: 'nebula',
		description: 'nebula - volume render experiment',
	},
	{
		type: 'image',
		src: new URL('../images/musgrave2.jpg', import.meta.url).href,
		name: 'untitled',
		description: '',
	},
	{
		type: 'image',
		src: new URL('../images/musgrave3.jpg', import.meta.url).href,
		name: 'untitled',
		description: '',
	},
	{
		type: 'image',
		src: new URL('../images/musgrave5.jpg', import.meta.url).href,
		name: 'untitled',
		description: '',
	},
	{
		type: 'image',
		src: new URL('../images/hdis.jpg', import.meta.url).href,
		name: 'hdis',
		description: '',
	},
	{
		type: 'image',
		src: new URL('../images/bw.jpg', import.meta.url).href,
		name: 'BW',
		description: '',
	},
	{
		type: 'text',
		description: 'coding',
	},
	{
		type: 'image',
		src: new URL('../images/YouTubeHistory_all.svg', import.meta.url).href,
		name: 'MYTH',
		description: 'My YouTube History - displays data of all videos, which where watched between mid 2016 and end 2019',
	},
	{
		type: 'image',
		src: new URL('../images/quakes3.jpg', import.meta.url).href,
		name: 'quakes',
		description: 'earthquake data transformed into circles',
	},
];
